<?php
/**
 * @version   $Id: Null.php 10831 2013-05-29 19:32:17Z btowles $
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2016 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/**
 *
 */
class RokCommon_Cache_Null extends RokCommon_Cache_AbstractCache
{
	/**
	 * Save data to cache
	 *
	 * @param string $groupName  Name of group of cache
	 * @param string $identifier Identifier of data - it should be unique in group
	 * @param mixed  $data       Data
	 *
	 * @internal param string $driver Driver strategy
	 *
	 * @throws RokCommon_Cache_Exception
	 * @return boolean
	 */
	public function set($groupName, $identifier, $data)
	{
		return true;
	}

	/**
	 * Gets data from cache
	 *
	 * @param string $groupName  Name of group
	 * @param string $identifier Identifier of data
	 *
	 * @internal param string $driver Driver strategy
	 *
	 * @throws RokCommon_Cache_Exception
	 * @return mixed
	 */
	public function get($groupName, $identifier)
	{
		return false;
	}

	/**
	 * Clears cache of specified identifier of group  with one/all drivers
	 *
	 *
	 * @param string $groupName  Name of group
	 * @param string $identifier Identifier
	 *
	 * @return boolean
	 */
	public function clearCache($groupName, $identifier)
	{
		return true;
	}

	/**
	 * Clears all cache generated by this class with one/all drivers
	 *
	 * @internal param string $driver Name of driver strategy
	 *
	 * @return boolean
	 */
	public function clearAllCache()
	{
		return true;
	}

	/**
	 * Clears cache of specified group  with one/all drivers
	 *
	 * @param string $groupName Name of group
	 *
	 * @return boolean
	 */
	public function clearGroupCache($groupName)
	{
		return true;
	}

	/**
	 * Check if cache data exists
	 *
	 *
	 * @param string $groupName  Name of group
	 * @param string $identifier Identifier
	 *
	 * @return boolean
	 */
	public function exists($groupName, $identifier)
	{
		return false;
	}
}
