<?php
/**
 * @var $this   N2View
 * @var $_class N2SmartsliderBackendSlidersView
 */

$groupID = N2Request::getInt('groupID', 0);
$group = false;

if ($groupID > 0) {
    $slidersModel = new N2SmartsliderSlidersModel();
    $group        = $slidersModel->get($groupID);
    N2HTML::heading(array(
        'title' => $group['title']
    ));
}
?>

<div class="n2-ss-sliders-outer-container">
    <?php
    N2SSBackendFragments::embedSliderManager($groupID, $group, $mode);
    ?>
</div>