<?php

N2Html::topBar(array(
    "actions" => array(
        N2Html::tag('a', array(
            'href'  => $this->appType->router->createUrl(array('sliders/index')),
            'class' => 'n2-button n2-button-normal n2-button-l n2-radius-s n2-button-red n2-h4 n2-b n2-uc'
        ), n2_('Cancel')),
        N2Html::tag('a', array(
            'href'    => '#',
            'class'   => 'n2-button n2-button-normal n2-button-l n2-radius-s n2-button-green n2-h4 n2-b n2-uc',
            'onclick' => 'return N2Classes.Form.submit("#smartslider-form");'
        ), n2_('Import'))
    )
));
?>

    <form id="smartslider-form" enctype="multipart/form-data" action="#" method="post">
    <?php
    N2SmartsliderSlidersModel::renderImportByUploadForm();
    ?>
        <input name="save" value="1" type="hidden"/>
</form>

    <div class="n2-form ">
    <div class="n2-form-tab ">
        <div class="n2-h2 n2-content-box-title-bg"><?php n2_e('Instructions'); ?></div>

        <div class="n2-description">
            <p><?php n2_e('You can upload the files which exported by Smart Slider 3.'); ?></p>

            <p><?php printf(n2_('Your server has an upload file limit at %s, so if you have bigger export file, please use the local import file method.'), @ini_get('post_max_size')); ?></p>
            <p><?php
                echo n2_('Local import file') . ': ';
                printf(n2_('Smart Slider export files are listed from the directory only with <i>.ss3</i> extension: %s'), N2Platform::getPublicDir()); ?>
            </p>
        </div>
    </div>
</div>
<?php N2SS3::showBeacon('Import slider'); ?>