<?php
/**
 * @var N2SmartsliderBackendGeneratorView $_class
 * @var N2SliderGeneratorPluginAbstract   $generatorGroup
 * @var N2GeneratorAbstract[]             $sources
 */
?>


<div class="n2-form-tab ">
    <div class="n2-h2 n2-content-box-title-bg"><?php echo n2_('Choose dynamic source') . ' - ' . $generatorGroup->getLabel(); ?></div>
    <?php

    foreach ($sources AS $source) {
        $url = $this->appType->router->createUrl(array(
            "generator/createSettings",
            array(
                "sliderid" => N2Request::getInt('sliderid'),
                "group"    => $generatorGroup->getName(),
                "type"     => $source->getName()
            )
        ));

        echo $_class->renderGeneratorBox($generatorGroup, N2Html::link($source->getLabel(), $url, array(
            "class" => "n2-button n2-button-normal n2-button-s n2-button-blue n2-radius-s n2-h5"
        )));
    }
    ?>
    <div class="n2-clear"></div>
</div>

<div style="height: 200px"></div>